"""initial schema

Revision ID: 81ae954d38d7
Revises: 
Create Date: 2026-08-12 17:22:36.003025
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '81ae954d38d7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector must exist before any Vector column is created. pg_trgm backs the
    # trigram search used by /questions/search.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=80), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interview_mix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('concepts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('parent_key', sa.String(length=200), nullable=True),
    sa.Column('display_name', sa.String(length=240), nullable=False),
    sa.Column('domain', sa.String(length=80), nullable=False),
    sa.Column('interview_type', sa.String(length=60), nullable=False),
    sa.Column('difficulty_floor', sa.Integer(), nullable=False),
    sa.Column('difficulty_ceiling', sa.Integer(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concepts'))
    )
    op.create_index(op.f('ix_concepts_key'), 'concepts', ['key'], unique=True)
    op.create_index(op.f('ix_concepts_parent_key'), 'concepts', ['parent_key'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_versions')),
    sa.UniqueConstraint('name', 'version', name='uq_prompt_name_version')
    )
    op.create_index(op.f('ix_prompt_versions_name'), 'prompt_versions', ['name'], unique=False)
    op.create_table('question_families',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('canonical_text', sa.Text(), nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('variant_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_families'))
    )
    op.create_index(op.f('ix_question_families_slug'), 'question_families', ['slug'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('role_family', sa.String(length=120), nullable=False),
    sa.Column('levels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('core_concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=True)
    op.create_table('rubrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('concept_key', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rubrics')),
    sa.UniqueConstraint('key', 'version', name='uq_rubric_key_version')
    )
    op.create_index(op.f('ix_rubrics_concept_key'), 'rubrics', ['concept_key'], unique=False)
    op.create_index(op.f('ix_rubrics_key'), 'rubrics', ['key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('target_company_slug', sa.String(length=120), nullable=True),
    sa.Column('target_role', sa.String(length=160), nullable=True),
    sa.Column('target_level', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_candidates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates')),
    sa.UniqueConstraint('user_id', name=op.f('uq_candidates_user_id'))
    )
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('follow_ups', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('role_family', sa.String(length=120), nullable=False),
    sa.Column('level', sa.String(length=60), nullable=True),
    sa.Column('interview_type', sa.String(length=60), nullable=False),
    sa.Column('concept_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('rubric_key', sa.String(length=200), nullable=True),
    sa.Column('question_origin', sa.String(length=40), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('based_on_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('copyright_status', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("question_origin IN ('observed', 'generated', 'user_submitted')", name=op.f('ck_questions_origin_enum')),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 5', name=op.f('ck_questions_difficulty_range')),
    sa.ForeignKeyConstraint(['family_id'], ['question_families.id'], name=op.f('fk_questions_family_id_question_families'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_index(op.f('ix_questions_family_id'), 'questions', ['family_id'], unique=False)
    op.create_index(op.f('ix_questions_interview_type'), 'questions', ['interview_type'], unique=False)
    op.create_index(op.f('ix_questions_level'), 'questions', ['level'], unique=False)
    op.create_index(op.f('ix_questions_rubric_key'), 'questions', ['rubric_key'], unique=False)
    op.create_index('ix_questions_type_difficulty', 'questions', ['interview_type', 'difficulty'], unique=False)
    op.create_table('candidate_skill_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('concept_key', sa.String(length=200), nullable=False),
    sa.Column('mastery', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('self_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('last_evidence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repetition_interval_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('mastery BETWEEN 0 AND 1', name=op.f('ck_candidate_skill_states_mastery_range')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_candidate_skill_states_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_skill_states')),
    sa.UniqueConstraint('candidate_id', 'concept_key', name='uq_candidate_concept')
    )
    op.create_index(op.f('ix_candidate_skill_states_candidate_id'), 'candidate_skill_states', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_skill_states_concept_key'), 'candidate_skill_states', ['concept_key'], unique=False)
    op.create_index(op.f('ix_candidate_skill_states_due_at'), 'candidate_skill_states', ['due_at'], unique=False)
    op.create_table('company_question_occurrences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.String(length=60), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('last_reported_on', sa.Date(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_question_occurrences_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_company_question_occurrences_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_question_occurrences')),
    sa.UniqueConstraint('company_id', 'question_id', 'level', name='uq_company_question_level')
    )
    op.create_index(op.f('ix_company_question_occurrences_company_id'), 'company_question_occurrences', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_question_occurrences_question_id'), 'company_question_occurrences', ['question_id'], unique=False)
    op.create_table('job_descriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=True),
    sa.Column('level', sa.String(length=60), nullable=True),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_job_descriptions_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_job_descriptions_company_id_companies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_descriptions'))
    )
    op.create_index(op.f('ix_job_descriptions_candidate_id'), 'job_descriptions', ['candidate_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=400), nullable=False),
    sa.Column('content_type', sa.String(length=160), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_resumes_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes'))
    )
    op.create_index(op.f('ix_resumes_candidate_id'), 'resumes', ['candidate_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=True),
    sa.Column('job_description_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('target_role', sa.String(length=200), nullable=False),
    sa.Column('target_level', sa.String(length=60), nullable=False),
    sa.Column('mode', sa.String(length=40), nullable=False),
    sa.Column('interview_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('thread_id', sa.String(length=80), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('final_scorecard', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("mode IN ('real', 'coaching', 'rapid_fire', 'coding', 'system_design', 'resume_defense', 'behavioral', 'full_loop')", name=op.f('ck_interview_sessions_mode_enum')),
    sa.CheckConstraint("status IN ('created', 'in_progress', 'awaiting_answer', 'completed', 'abandoned')", name=op.f('ck_interview_sessions_status_enum')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_interview_sessions_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_interview_sessions_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], name=op.f('fk_interview_sessions_job_description_id_job_descriptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_interview_sessions_resume_id_resumes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_sessions')),
    sa.UniqueConstraint('thread_id', name=op.f('uq_interview_sessions_thread_id'))
    )
    op.create_index(op.f('ix_interview_sessions_candidate_id'), 'interview_sessions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_status'), 'interview_sessions', ['status'], unique=False)
    op.create_table('resume_claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=60), nullable=False),
    sa.Column('technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('concept_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('has_metric', sa.Boolean(), nullable=False),
    sa.Column('probe_priority', sa.Integer(), nullable=False),
    sa.Column('support_level', sa.String(length=40), nullable=True),
    sa.Column('support_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_claims_resume_id_resumes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_claims'))
    )
    op.create_index('ix_resume_claims_priority', 'resume_claims', ['resume_id', 'probe_priority'], unique=False)
    op.create_index(op.f('ix_resume_claims_resume_id'), 'resume_claims', ['resume_id'], unique=False)
    op.create_table('interview_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('question_id', sa.Uuid(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('interview_type', sa.String(length=60), nullable=False),
    sa.Column('agent_key', sa.String(length=60), nullable=False),
    sa.Column('concept_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rubric_key', sa.String(length=200), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('is_followup', sa.Boolean(), nullable=False),
    sa.Column('probe_reason', sa.Text(), nullable=True),
    sa.Column('asks_confidence', sa.Boolean(), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=120), nullable=True),
    sa.Column('asked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['interview_questions.id'], name=op.f('fk_interview_questions_parent_id_interview_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_interview_questions_question_id_questions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('fk_interview_questions_session_id_interview_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_questions')),
    sa.UniqueConstraint('session_id', 'ordinal', name='uq_session_ordinal')
    )
    op.create_index(op.f('ix_interview_questions_session_id'), 'interview_questions', ['session_id'], unique=False)
    op.create_index('ix_interview_questions_session_ordinal', 'interview_questions', ['session_id', 'ordinal'], unique=False)
    op.create_table('misconceptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('concept_key', sa.String(length=200), nullable=False),
    sa.Column('belief', sa.Text(), nullable=False),
    sa.Column('correction', sa.Text(), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('times_observed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_misconceptions_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('fk_misconceptions_session_id_interview_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_misconceptions'))
    )
    op.create_index(op.f('ix_misconceptions_candidate_id'), 'misconceptions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_misconceptions_concept_key'), 'misconceptions', ['concept_key'], unique=False)
    op.create_table('study_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_study_plans_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('fk_study_plans_session_id_interview_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_plans'))
    )
    op.create_index(op.f('ix_study_plans_candidate_id'), 'study_plans', ['candidate_id'], unique=False)
    op.create_table('candidate_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interview_question_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=40), nullable=True),
    sa.Column('self_confidence', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('self_confidence IS NULL OR self_confidence BETWEEN 1 AND 5', name=op.f('ck_candidate_answers_self_confidence_range')),
    sa.ForeignKeyConstraint(['interview_question_id'], ['interview_questions.id'], name=op.f('fk_candidate_answers_interview_question_id_interview_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_answers'))
    )
    op.create_index(op.f('ix_candidate_answers_interview_question_id'), 'candidate_answers', ['interview_question_id'], unique=True)
    op.create_table('replay_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_session_id', sa.Uuid(), nullable=False),
    sa.Column('replay_session_id', sa.Uuid(), nullable=True),
    sa.Column('from_question_id', sa.Uuid(), nullable=True),
    sa.Column('checkpoint_id', sa.String(length=120), nullable=False),
    sa.Column('original_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('replay_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('improvement_delta', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_question_id'], ['interview_questions.id'], name=op.f('fk_replay_sessions_from_question_id_interview_questions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_session_id'], ['interview_sessions.id'], name=op.f('fk_replay_sessions_original_session_id_interview_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replay_session_id'], ['interview_sessions.id'], name=op.f('fk_replay_sessions_replay_session_id_interview_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_replay_sessions'))
    )
    op.create_index(op.f('ix_replay_sessions_original_session_id'), 'replay_sessions', ['original_session_id'], unique=False)
    op.create_table('study_plan_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('concept_key', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('learn_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('practice_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reattempt_question_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['study_plans.id'], name=op.f('fk_study_plan_items_plan_id_study_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reattempt_question_id'], ['interview_questions.id'], name=op.f('fk_study_plan_items_reattempt_question_id_interview_questions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_plan_items'))
    )
    op.create_index(op.f('ix_study_plan_items_plan_id'), 'study_plan_items', ['plan_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('answer_id', sa.Uuid(), nullable=False),
    sa.Column('judge_key', sa.String(length=60), nullable=False),
    sa.Column('rubric_key', sa.String(length=200), nullable=True),
    sa.Column('score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('communication_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('judge_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('demonstrated', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('incorrect', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_quotes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('prompt_name', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('score BETWEEN 0 AND 1', name=op.f('ck_evaluations_score_range')),
    sa.ForeignKeyConstraint(['answer_id'], ['candidate_answers.id'], name=op.f('fk_evaluations_answer_id_candidate_answers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations')),
    sa.UniqueConstraint('answer_id', 'judge_key', name='uq_answer_judge')
    )
    op.create_index(op.f('ix_evaluations_answer_id'), 'evaluations', ['answer_id'], unique=False)
    op.create_table('skill_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('concept_key', sa.String(length=200), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('answer_id', sa.Uuid(), nullable=True),
    sa.Column('score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('self_confidence', sa.Integer(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('is_followup', sa.Boolean(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['candidate_answers.id'], name=op.f('fk_skill_evidence_answer_id_candidate_answers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_skill_evidence_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('fk_skill_evidence_session_id_interview_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_evidence'))
    )
    op.create_index('ix_skill_evidence_candidate_concept', 'skill_evidence', ['candidate_id', 'concept_key'], unique=False)
    op.create_index(op.f('ix_skill_evidence_candidate_id'), 'skill_evidence', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_skill_evidence_concept_key'), 'skill_evidence', ['concept_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_evidence_concept_key'), table_name='skill_evidence')
    op.drop_index(op.f('ix_skill_evidence_candidate_id'), table_name='skill_evidence')
    op.drop_index('ix_skill_evidence_candidate_concept', table_name='skill_evidence')
    op.drop_table('skill_evidence')
    op.drop_index(op.f('ix_evaluations_answer_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_study_plan_items_plan_id'), table_name='study_plan_items')
    op.drop_table('study_plan_items')
    op.drop_index(op.f('ix_replay_sessions_original_session_id'), table_name='replay_sessions')
    op.drop_table('replay_sessions')
    op.drop_index(op.f('ix_candidate_answers_interview_question_id'), table_name='candidate_answers')
    op.drop_table('candidate_answers')
    op.drop_index(op.f('ix_study_plans_candidate_id'), table_name='study_plans')
    op.drop_table('study_plans')
    op.drop_index(op.f('ix_misconceptions_concept_key'), table_name='misconceptions')
    op.drop_index(op.f('ix_misconceptions_candidate_id'), table_name='misconceptions')
    op.drop_table('misconceptions')
    op.drop_index('ix_interview_questions_session_ordinal', table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_session_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index(op.f('ix_resume_claims_resume_id'), table_name='resume_claims')
    op.drop_index('ix_resume_claims_priority', table_name='resume_claims')
    op.drop_table('resume_claims')
    op.drop_index(op.f('ix_interview_sessions_status'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_candidate_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_resumes_candidate_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_job_descriptions_candidate_id'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    op.drop_index(op.f('ix_company_question_occurrences_question_id'), table_name='company_question_occurrences')
    op.drop_index(op.f('ix_company_question_occurrences_company_id'), table_name='company_question_occurrences')
    op.drop_table('company_question_occurrences')
    op.drop_index(op.f('ix_candidate_skill_states_due_at'), table_name='candidate_skill_states')
    op.drop_index(op.f('ix_candidate_skill_states_concept_key'), table_name='candidate_skill_states')
    op.drop_index(op.f('ix_candidate_skill_states_candidate_id'), table_name='candidate_skill_states')
    op.drop_table('candidate_skill_states')
    op.drop_index('ix_questions_type_difficulty', table_name='questions')
    op.drop_index(op.f('ix_questions_rubric_key'), table_name='questions')
    op.drop_index(op.f('ix_questions_level'), table_name='questions')
    op.drop_index(op.f('ix_questions_interview_type'), table_name='questions')
    op.drop_index(op.f('ix_questions_family_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rubrics_key'), table_name='rubrics')
    op.drop_index(op.f('ix_rubrics_concept_key'), table_name='rubrics')
    op.drop_table('rubrics')
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_question_families_slug'), table_name='question_families')
    op.drop_table('question_families')
    op.drop_index(op.f('ix_prompt_versions_name'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_concepts_parent_key'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_key'), table_name='concepts')
    op.drop_table('concepts')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
